"use client";

import { BrandBookType } from "@/lib/types";
import { getActiveTemplate } from "@/lib/templates";
import { Button, Card } from "./ui";
import { StepHeader } from "./StepHeader";

const TYPES: BrandBookType[] = ["MINIMAL", "MEDIUM", "PREMIUM"];

export function ScreenStart({
  selected,
  onSelect,
  onNext,
}: {
  selected: BrandBookType | null;
  onSelect: (type: BrandBookType) => void;
  onNext: () => void;
}) {
  return (
    <div className="min-h-screen">
      <StepHeader step={1} />
      <main className="mx-auto flex max-w-5xl flex-col items-center px-6 py-20 text-center">
        <h1 className="text-3xl font-semibold tracking-tight text-ink-900 sm:text-4xl">
          Brand Book Generator
        </h1>
        <p className="mt-3 max-w-xl text-balance text-ink-500">
          Transform your project brief into ready-to-use brand book content.
        </p>

        <div className="mt-12 grid w-full grid-cols-1 gap-4 sm:grid-cols-3">
          {TYPES.map((type) => {
            const template = getActiveTemplate(type);
            const isSelected = selected === type;
            return (
              <button
                key={type}
                onClick={() => onSelect(type)}
                className={
                  "focus-ring rounded-2xl border p-6 text-left transition-all " +
                  (isSelected
                    ? "border-turquoise-400 bg-white shadow-card ring-2 ring-turquoise-300"
                    : "border-ink-200 bg-white/60 hover:border-turquoise-300 hover:bg-white")
                }
              >
                <div className="flex items-center justify-between">
                  <span className="text-base font-semibold text-ink-900">{template.label}</span>
                  <span
                    className={
                      "flex h-5 w-5 items-center justify-center rounded-full border-2 " +
                      (isSelected ? "border-turquoise-500 bg-turquoise-500" : "border-ink-300")
                    }
                  >
                    {isSelected && (
                      <span className="h-1.5 w-1.5 rounded-full bg-white" />
                    )}
                  </span>
                </div>
                <p className="mt-1.5 text-xs font-medium uppercase tracking-wide text-turquoise-600">
                  ~{template.approxPageCount} pages · {template.pages.length} sections to generate
                </p>
                <p className="mt-3 text-sm leading-relaxed text-ink-500">
                  {template.description}
                </p>
              </button>
            );
          })}
        </div>

        <Card className="mt-10 w-full p-4 text-left">
          <p className="text-xs font-medium uppercase tracking-wide text-ink-400">
            What gets generated
          </p>
          <p className="mt-1.5 text-sm text-ink-600">
            Only the pages that require project-specific copy are generated by AI. Every other
            page of the template stays untouched, ready to export as-is.
          </p>
        </Card>

        <Button
          className="mt-8"
          onClick={onNext}
          disabled={!selected}
        >
          Continue
        </Button>
      </main>
    </div>
  );
}
